/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Tickets: () => import('#controllers/tickets_controller'),
  Categories: () => import('#controllers/categories_controller'),
}
