/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['id', 'name'] as const
  $columns = CategorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class NametagSchema extends BaseModel {
  static $columns = ['color', 'id', 'name'] as const
  $columns = NametagSchema.$columns
  @column()
  declare color: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class TicketTagSchema extends BaseModel {
  static $columns = ['id', 'nametagId', 'ticketId'] as const
  $columns = TicketTagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nametagId: number | null
  @column()
  declare ticketId: number | null
}

export class TicketSchema extends BaseModel {
  static $columns = ['archivedAt', 'bugLink', 'categoryId', 'clientComment', 'createdAt', 'id', 'mailComment', 'teamComment', 'ticketStatusId', 'title', 'updatedAt', 'userId'] as const
  $columns = TicketSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare bugLink: string
  @column()
  declare categoryId: number | null
  @column()
  declare clientComment: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mailComment: string | null
  @column()
  declare teamComment: string | null
  @column()
  declare ticketStatusId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TicketsStatusSchema extends BaseModel {
  static $columns = ['id', 'name'] as const
  $columns = TicketsStatusSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class UserSchema extends BaseModel {
  static $columns = ['companyName', 'createdAt', 'deletedAt', 'drivePath', 'firstname', 'id', 'lastname', 'mail', 'password', 'role', 'session', 'tel', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare drivePath: string | null
  @column()
  declare firstname: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastname: string | null
  @column()
  declare mail: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column()
  declare session: string | null
  @column()
  declare tel: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WebsiteSchema extends BaseModel {
  static $columns = ['id', 'url', 'userId'] as const
  $columns = WebsiteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare url: string
  @column()
  declare userId: number | null
}
